name: Supply chain

on:
  push:
  pull_request:
  schedule:
    - cron: "23 7 * * 1"

permissions:
  contents: read

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: EmbarkStudios/cargo-deny-action@v2
